services:
  # Layanan untuk Web Server (PHP + Apache)
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  # Layanan untuk Database (MySQL)
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password_rahasia
      MYSQL_DATABASE: db_listrik
      MYSQL_USER: AgungWidySaputro
      MYSQL_PASSWORD: Aws280803
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: